name: "build"
on:
  workflow_dispatch

jobs:
  build-ink:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - uses: engineerd/configurator@v0.0.8
      with:
        name: "inklecate"
        fromGitHubReleases: "true"
        repo: "inkle/ink"
        urlTemplate: "https://github.com/inkle/ink/releases/download/{{version}}/inklecate_linux.zip"
        version: "latest"
        token: ${{ secrets.GITHUB_TOKEN }}
        pathInArchive: "inklecate"
    - name: Testing
      run: |
        ls /home/runner/configurator/bin/
        /home/runner/configurator/bin/inklecate
        inklecate
    - name: install app dependencies and build it
      run: yarn && yarn ink && yarn build
    